첫번째 과제
ExodusEnt-Android/AndroidCleanArchitecture pull request #10
Opened 2022-11-09 07:28 UTC by mingue0605

2022-11-09 08:26 UTC, realizer12 requested changes

2022-11-09 08:26 UTC, realizer12 commented on .gitignore
> +local.properties
여기  gitignore  추가 
https://www.toptal.com/developers/gitignore. 확인 해주세엽

2022-11-09 08:26 UTC, realizer12 commented on app/src/main/AndroidManifest.xml
> +        android:allowBackup="true"
allowBackUp. 이유가 없다면 false로 해주세엽  아래  링크 참고 
https://velog.io/@dooooreeee/%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-allowBackup

2022-11-09 08:26 UTC, realizer12 commented on app/src/main/AndroidManifest.xml
> +            android:windowSoftInputMode="adjustPan">
main activity.에서  adjustpan을 사용하는 경우가 있나엽??
없으면 빼주세엽~

2022-11-09 08:26 UTC, realizer12 commented on presentation/build.gradle
> +    def nav_version = "2.3.3"
요런건   각  필요  imple  위에다가  넣어주는게 어떤가엽??
그리고 현재   nav_version 안쓰고 있는거 같아엽

ex)
 def nav_version = "2.3.3"
implementation 'androidx.navigation:navigation-fragment-ktx:2.5.3'
implementation 'androidx.navigation:navigation-ui-ktx:2.5.3'

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Activity/LoginActivity.kt
> +class LoginActivity : AppCompatActivity() {
민규님 요거  다음과제에  base 처리로 activity랑  fragment 추가 해주세엽~!

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Activity/LoginActivity.kt
> +                startActivity(Intent(this, MainActivity::class.java))
요거는 코드 빼주세엽~!

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Activity/SplashActivity.kt
> +    private var mHandler = Handler()
요거는  안쓰는  코드같은데  빼주세엽~!

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Adapter/NewsListAdapter.kt
> +    inner class ViewHolder(view:View) : RecyclerView.ViewHolder(view){
뷰홀더는  외부로 빼주는게  좋을거 같습니다~!

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Adapter/NewsListAdapter.kt
> +            val listener = View.OnClickListener { view ->
리스너가 여기로 들어오면,  item bind시마다   계속  리스너가 set 되어질것 같아엽
onCreateViewHolder. 에서  처리하는게 어떤가엽??

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Adapter/NewsListAdapter.kt
> +    fun setItems(@NonNull items: List<Items>) {
dto. 명이 Items는  어떤  역할인지   알기 어려운거 같습니다~    NewsItems 등으로 바꾸는게 좋을거 같아엽~

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Adapter/NewsListAdapter.kt
> +    }
setItems가  리스트 업데이트 후,  뷰 변환까지를  하는게 깔끔해보입니다!
이렇게 쓸경우  notifydatasetchanged를  외부보단  여기에서 부르는게  좋을거 같아엽~

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/ApiService.kt
> +    fun requestNews(): Call<NewsData>
country ,  key는   변할수 있는 값들이라서
@Query   어노테이션으로  query구문을 다  바꾸는게 좋을거 같아엽~!

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/ApiService.kt
> +    ) : Call<NewsData>
api key는  local properties에서 관리하는 방식으로 바꿔주세엽~

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Fragment/CategoryBtnFragment.kt
> +                val item = bundleOf("category" to "business")
여기 entertain인거 같은데 잘못 들어간거 같아엽~

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Fragment/CategoryBtnFragment.kt
> +                navController.navigate(R.id.categoryNewsFragment, item)
이렇게  나뉘는경우,  xml 에  버튼별  lable을 지정하거나  enum class 를 사용하여,  코드를  줄이는게  좋을거 같아엽~
그렇게 해서 navController.navigate(R.id.categoryNewsFragment, item)  요거 하나만 쓰도록 해주세엽~!

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Fragment/CategoryNewsFragment.kt
> +        mBinding.rvCategory.layoutManager = LinearLayoutManagerWrapper(requireContext(), LinearLayoutManager.VERTICAL, false)
layoutmanager는  xml 에  적용해서  코드를 더 줄일수 있을거 같아엽~!

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Fragment/CategoryNewsFragment.kt
> +        val retrofit = Retrofit.Builder().baseUrl("https://newsapi.org/v2/")
baseurl  따로  관리 하게 해주세엽~!

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Fragment/CategoryNewsFragment.kt
> +        val retrofit = Retrofit.Builder().baseUrl("https://newsapi.org/v2/")
음 매번 api 사용시마다 retorift 설정 코드가 들어가는거 같은데, 
retrofit 코드도  이유가 없다면, singletone으로 관리하는게 좋을거 같습니다.

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Fragment/CategoryNewsFragment.kt
> +            R.id.tv_author, R.id.tv_title, R.id.iv_photo -> {
모두 같은 클릭 처리라면,    constraintlayout에서  group으로 묶는게 어떤가엽??
이렇게 하면,  같은 클릭이벤트가 추가될때  xml에서 해당 뷰를  group으로  묶어서 추가할수 있을거 같아엽
여기서는 group에 대한 클릭으로 처리하고엽

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Fragment/NewsDetailFragment.kt
> +                mBinding.ivSaved.setImageResource(R.drawable.star_ok)
Dispatcher io 로 설정된 상태에서   뷰 동작은  다시  main 쓰레드로  바꿔주어야 할거 같은데 어떤가엽??

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Fragment/SavedFragment.kt
> +        saveNewsAdapter = context?.let { NewsListAdapter(it, this) }
여기선 왜 그냥 context로 사용하나엽??
현재 fragment에서만  사용되는  애들이라서 ,  requireactivity같이  activity context로  접근하는게 좋을거 같아엽~

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Fragment/TopNewsFragment.kt
> +        super.onCreate(savedInstanceState)
onCreate 안쓰면 없애주세엽~

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/LinearLayoutManagerWrapper.kt
> +class LinearLayoutManagerWrapper : LinearLayoutManager {
음  이  wrapper 클래스는  왜  만들어졌나엽??

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/NewsData.kt
> +@Entity
이건 local table로 안쓰는거 같은데  왜  Entity 어노테이션이 들어갔나엽??

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Room/NewsDB.kt
> +                        .fallbackToDestructiveMigration()
database 명칭이 안맞는거 같아엽. 
그리고 보통  앱내  로컬 database는 한개로  사용을 많이해서,  global 한 이름으로 쓴다고 합니다~!
local-database.db 등등

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Adapter/NewsListAdapter.kt
> +class NewsListAdapter (
민규님 이거 ListAdapter 상속 받고,  difutil 사용으로 바꿔주세엽~

2022-11-09 08:26 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Activity/SplashActivity.kt
> +    }
스플래시에서  로그인 되어있는지 여부를 체크해야될것 같습니다.~
지금은 로그인화면에서 로그인을 해도  메인으로 안가지고 로그인으로 가지는것 같아엽~1

2022-11-09 10:06 UTC, mingue0605 commented on presentation/src/main/java/com/example/presentation/Adapter/NewsListAdapter.kt
> +class NewsListAdapter (
이건 먼지 모르게씀;;

2022-11-09 10:07 UTC, mingue0605 commented on presentation/src/main/java/com/example/presentation/LinearLayoutManagerWrapper.kt
> +class LinearLayoutManagerWrapper : LinearLayoutManager {
리사이클러뷰 간단하게 쓰려고 애돌에서 긁어왔는뎁 뺄까여

2022-11-10 08:35 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Room/NewsDB.kt
> +                        .fallbackToDestructiveMigration()
[eb284c6](https://github.com/ExodusEnt-Android/AndroidCleanArchitecture/pull/10/commits/eb284c6e5b29946c27e6a27cdeaa5651d2e97325)

2022-11-16 01:45 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/LinearLayoutManagerWrapper.kt
> +class LinearLayoutManagerWrapper : LinearLayoutManager {
사용용도가 머에엽??

2022-11-16 01:46 UTC, realizer12 commented on presentation/src/main/java/com/example/presentation/Adapter/NewsListAdapter.kt
> +class NewsListAdapter (
https://s2choco.tistory.com/33. 요거 함 봐보삼

2022-11-18 07:58 UTC, closed without merging

2022-11-18 07:59 UTC, mingue0605 commented
어쩔