HW-6 DI의존성 추가
ExodusEnt-Android/AndroidCleanArchitecture pull request #24
Opened 2023-03-18 04:39 UTC by jnugg0819

HW-6 Hilt를 이용한 DI추가

2023-03-22 15:58 UTC, realizer12 requested changes

2023-03-22 15:58 UTC, realizer12 commented on local/src/main/java/org/techtown/local/feature/di/LocalModule.kt
> +    ) : ArticlesDao = AppDatabase.getInstance(context).articleDao()
상미님 지금 현재는 local database의 경우 내부 의존성이 생겨있는 상태이기때문에
외부 의존성으로바꿔 주는게 좋을거  같아엽
AppDatabas도  hilt 처리 해주세엽~!

2023-03-22 15:58 UTC, realizer12 commented on presentation/src/main/java/org/techtown/presentation/feature/main/viewmodel/SavedViewModel.kt
> +class SavedViewModel @Inject constructor(
상미님 여기 동작 이상해서 살펴보니까
shouldRequestViewMore 이 필요없는 코드 같아엽
그리고 if (presentArticles.isNotEmpty()) 이거 false일때는 
list clear 를 해주어야 할것 같은데  확인점 

그리고 탭전환시 업데이트 안되는 문제때문에 getSavedArticleList 요놈은 fragment쪽
init에 들어가는게 좋을거 같아엽.

bottom nav사용시에는 fragment destory되어도 fragment용  viewmodel clear 가 안되는거 같아엽
이거는 좀더 알아봐야 할거 같은데
이문제대문에   탭왔다갔다했을때 ,   getSavedArticleList가 업데이트 안되는즁

2023-03-29 12:24 UTC, jnugg0819 commented on presentation/src/main/java/org/techtown/presentation/feature/main/viewmodel/SavedViewModel.kt
> +class SavedViewModel @Inject constructor(
@realizer12 동훈님 이거 멘트 이상한데다 단거같은데 맞져?

2023-03-29 12:26 UTC, jnugg0819 commented on local/src/main/java/org/techtown/local/feature/di/LocalModule.kt
> +    ) : ArticlesDao = AppDatabase.getInstance(context).articleDao()
9dbe0b7abcb7244eea951f5685f5945a2c8070e5

2023-03-29 12:59 UTC, jnugg0819 commented on presentation/src/main/java/org/techtown/presentation/feature/main/viewmodel/SavedViewModel.kt
> +class SavedViewModel @Inject constructor(
98c36908e5bcca32bcd179a54f30756f58373e48

2023-03-29 13:54 UTC, realizer12 commented on presentation/src/main/java/org/techtown/presentation/feature/main/viewmodel/SavedViewModel.kt
> +class SavedViewModel @Inject constructor(
야스   맞아엽 ㅋㅋㅋ
상미님이 고친 부분 말한거 마즘  👍

2023-03-29 13:55 UTC, realizer12 approved these changes

2023-03-29 13:58 UTC, merged